/**
 * Pure, deterministic renderers for the per-adapter reference.
 *
 * `renderReferenceMarkdown()` produces `docs/adapter-reference.md` and
 * `renderFeatureRecordSchema()` produces the object serialised to
 * `public/schema/v1/feature-record.schema.json`. Both are driven solely by
 * `ADAPTER_REFERENCE` (no clock, no environment), so the byte-identity
 * spec can re-render them and compare to the checked-in files. Regenerate
 * with `yarn adapters:sync`.
 */

import {
  ADAPTER_REFERENCE,
  FEATURE_RECORD_FIELDS,
  type AdapterDoc,
  type GenericAdapterDoc,
  type DomainAdapterDoc,
  type FieldDoc,
} from './adapter-reference';

const PAGES_BASE = 'https://ebi-webcomponents.github.io/protvista';
const GITHUB_BLOB = 'https://github.com/ebi-webcomponents/protvista/blob/next';
const GITHUB_TREE = 'https://github.com/ebi-webcomponents/protvista/tree/next';

export const FEATURE_RECORD_SCHEMA_ID = `${PAGES_BASE}/schema/v1/feature-record.schema.json`;

/** Filenames produced by the generator, relative to the repo root. */
export const FEATURE_RECORD_SCHEMA_PATH = 'public/schema/v1/feature-record.schema.json';
// The Starlight docs page (Astro content collection). Base-prefixed in-site
// links (`/protvista/...`) and absolute GitHub/hosted URLs are emitted so the
// page renders correctly under the site base with no relative-path breakage.
export const ADAPTER_REFERENCE_MD_PATH =
  'docs/src/content/docs/adapter-reference.md';

const isGeneric = (d: AdapterDoc): d is GenericAdapterDoc => d.tier === 'generic';
const isDomain = (d: AdapterDoc): d is DomainAdapterDoc => d.tier === 'domain';

/** Escape a value for use inside a Markdown table cell. */
function cell(value: string): string {
  return value.replace(/\|/g, '\\|');
}

function fieldTable(fields: readonly FieldDoc[]): string {
  const header = '| Field | Type | Required | Notes |\n|---|---|---|---|';
  const rows = fields.map(
    (f) =>
      `| \`${f.name}\` | ${f.type} | ${f.required ? 'Yes' : 'No'} | ${cell(
        f.notes ?? ''
      )} |`
  );
  return [header, ...rows].join('\n');
}

function genericSection(d: GenericAdapterDoc): string {
  const parts: string[] = [];
  parts.push(`### \`${d.name}\` — ${d.title}`);
  parts.push('');
  parts.push(d.summary);
  parts.push('');
  parts.push(
    `- **File extension:** \`${d.ext}\` — **fetched as:** ${d.body}`
  );
  if (d.headerColumns) {
    parts.push(
      `- **Header row (required columns):** \`${d.headerColumns.join(',')}\` — plus optional \`score\`.`
    );
  }
  if (d.coordinateNote) {
    parts.push(`- ${d.coordinateNote}`);
  }
  parts.push('');
  parts.push(fieldTable(d.fields));
  return parts.join('\n');
}

function domainTable(docs: readonly DomainAdapterDoc[]): string {
  const header =
    '| Semantic kind | Adapter | Renders with | Inputs | Input shape |\n|---|---|---|---|---|';
  const rows = docs.map((d) => {
    const inputs = d.fetchesSecondaryUrl
      ? `${d.inputs} (+ fetches a further URL)`
      : String(d.inputs);
    return `| \`${d.kind}\` | \`${d.name}\` | \`${d.component}\` | ${inputs} | ${cell(
      d.inputSummary
    )} |`;
  });
  return [header, ...rows].join('\n');
}

export function renderReferenceMarkdown(
  reference: readonly AdapterDoc[] = ADAPTER_REFERENCE
): string {
  const generic = reference.filter(isGeneric);
  const domain = reference.filter(isDomain);

  const lines: string[] = [];
  lines.push('---');
  lines.push('title: Built-in adapter reference');
  lines.push('---');
  lines.push('');
  lines.push(
    '<!-- Generated by `yarn adapters:sync` from src/schema/adapters/adapter-reference.ts. Do not edit by hand. -->'
  );
  lines.push('');
  lines.push(
    'ProtVista *configuration* (rows, tracks, sources, rendering) is validated by the ' +
      `[config JSON Schema](${PAGES_BASE}/schema/v1/config.schema.json); *track payloads* — the shapes ` +
      'adapters consume — are not. This page fills that gap: the expected input shape for every ' +
      'built-in adapter. For the config-vs-payload boundary see ' +
      '[Configuration vs data](/protvista/configuration-vs-data); for the normative generic-format ' +
      `contract see [specs/generic-format-adapters.md](${GITHUB_BLOB}/specs/generic-format-adapters.md).`
  );
  lines.push('');
  lines.push(
    'This reference is generated from the adapter code and kept in sync by drift tests, so it ' +
      'cannot silently diverge. It is a reference aid, not a normative schema.'
  );
  lines.push('');

  lines.push('## Bring-your-own-data formats');
  lines.push('');
  lines.push(
    'These four adapters parse a file **you** supply and emit the canonical *feature record* ' +
      '(`type`, `start`, `end`, optional `description`/`score`). Point a track at a local file ' +
      'whose extension selects the adapter (e.g. `data: ./hotspots.csv`), or set `adapter:` ' +
      'explicitly. A machine-readable schema for this record is served at ' +
      `[\`feature-record.schema.json\`](${FEATURE_RECORD_SCHEMA_ID}) ` +
      `(published at \`${FEATURE_RECORD_SCHEMA_ID}\`).`
  );
  lines.push('');
  for (const d of generic) {
    lines.push(genericSection(d));
    lines.push('');
  }

  lines.push('## Built-in track adapters (provider-supplied)');
  lines.push('');
  lines.push(
    'These adapters back the built-in semantic `kind`s. Their input is a response from an EBI ' +
      'API (or equivalent provider) — you do **not** author these payloads; you point a track at ' +
      'the source URL and the adapter transforms the response. The shapes below are informational ' +
      '(useful when swapping an endpoint or writing a custom adapter for a kind), not a contract ' +
      'you must produce.'
  );
  lines.push('');
  lines.push(domainTable(domain));
  lines.push('');

  lines.push('## Related');
  lines.push('');
  lines.push(
    '- [Configuration vs data](/protvista/configuration-vs-data) — what config controls vs what providers supply.'
  );
  lines.push(
    `- [specs/config-approach.md](${GITHUB_BLOB}/specs/config-approach.md) — normative Intent/Representation split.`
  );
  lines.push(
    `- [specs/generic-format-adapters.md](${GITHUB_BLOB}/specs/generic-format-adapters.md) — normative generic-format contract.`
  );
  lines.push(
    `- [examples/](${GITHUB_TREE}/examples) — runnable, CI-validated config + data pairs.`
  );
  lines.push(
    '- Shape-correct mocks (#150) and React integration (#155) track downstream ownership of these shapes.'
  );
  lines.push('');
  lines.push(
    '_Licensed under [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)._'
  );
  lines.push('');
  return lines.join('\n');
}

export function renderFeatureRecordSchema(): Record<string, unknown> {
  const properties: Record<string, Record<string, unknown>> = {};
  for (const f of FEATURE_RECORD_FIELDS) {
    const prop: Record<string, unknown> = { type: f.type };
    if (f.notes) prop.description = f.notes;
    if (f.name === 'start') {
      prop.description =
        '1-based start position (inclusive).';
      prop.$comment =
        'features-json also accepts `begin` as an alias for `start`; `start` wins when both are present.';
    }
    properties[f.name] = prop;
  }
  return {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: FEATURE_RECORD_SCHEMA_ID,
    title: 'ProtVista feature record',
    description:
      'The canonical payload the generic bring-your-own-data adapters (features-csv, features-tsv, features-json, bed) emit and the feature tracks consume. Generic format only — domain-adapter (EBI API) payloads are not schematised. See docs/adapter-reference.md.',
    type: 'object',
    required: FEATURE_RECORD_FIELDS.filter((f) => f.required).map((f) => f.name),
    additionalProperties: true,
    properties,
  };
}

/** Serialised form written to `public/schema/v1/feature-record.schema.json`. */
export function renderFeatureRecordSchemaJson(): string {
  return `${JSON.stringify(renderFeatureRecordSchema(), null, 2)}\n`;
}
